import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpenCheck, Building2, Database, GraduationCap, Plus, Users } from "lucide-react";
import { useMemo, useState } from "react";

import { api } from "../api";
import { Badge, Card, ErrorNotice, Spinner } from "../components/ui";

export function AdminApp({ view }: { view: string }) {
  const client = useQueryClient();
  const grades = useQuery({ queryKey: ["grades"], queryFn: api.grades });
  const users = useQuery({ queryKey: ["admin-users"], queryFn: api.adminUsers });
  const [selectedClass, setSelectedClass] = useState<number | null>(null);
  const [selectedTeacher, setSelectedTeacher] = useState<number | null>(null);
  const [selectedStudent, setSelectedStudent] = useState<number | null>(null);
  const [newClass, setNewClass] = useState({ grade: 1, section: "A", name: "Grade 1A", subject: "General Studies" });
  const teachers = useMemo(() => users.data?.filter(item => item.role === "teacher") ?? [], [users.data]);
  const students = useMemo(() => users.data?.filter(item => item.role === "student") ?? [], [users.data]);
  const assignTeacher = useMutation({ mutationFn: () => api.assignTeacher(selectedClass!, selectedTeacher!), onSuccess: () => client.invalidateQueries({ queryKey: ["grades"] }) });
  const placeStudent = useMutation({ mutationFn: () => api.placeStudent(selectedClass!, selectedStudent!), onSuccess: () => { client.invalidateQueries({ queryKey: ["grades"] }); client.invalidateQueries({ queryKey: ["admin-users"] }); } });
  const createClass = useMutation({
    mutationFn: () => api.createClass(newClass),
    onSuccess: () => client.invalidateQueries({ queryKey: ["grades"] }),
  });
  if (grades.isLoading || users.isLoading) return <div className="center-loader"><Spinner /></div>;
  if (grades.error || users.error) return <ErrorNotice message={((grades.error || users.error) as Error).message} />;
  const allClasses = grades.data?.flatMap(item => item.classes) ?? [];
  if (view === "assignments") return <><div className="page-heading"><div><span className="eyebrow">People and access</span><h1>Class assignments</h1><p>Teachers may manage several classes. Every student has exactly one active class.</p></div></div><div className="two-column"><Card><div className="card-heading"><div><span className="eyebrow">Teacher assignment</span><h2>Add a teacher to a class</h2></div><Users /></div><label className="form-label">Class<select value={selectedClass ?? ""} onChange={event => setSelectedClass(Number(event.target.value))}><option value="">Select class</option>{allClasses.map(item => <option key={item.id} value={item.id}>Grade {item.grade}{item.section} · {item.subject}</option>)}</select></label><label className="form-label">Teacher<select value={selectedTeacher ?? ""} onChange={event => setSelectedTeacher(Number(event.target.value))}><option value="">Select teacher</option>{teachers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="primary-button full" disabled={!selectedClass || !selectedTeacher || assignTeacher.isPending} onClick={() => assignTeacher.mutate()}>Assign teacher</button></Card><Card><div className="card-heading"><div><span className="eyebrow">Student placement</span><h2>Move student to one class</h2></div><GraduationCap /></div><label className="form-label">Class<select value={selectedClass ?? ""} onChange={event => setSelectedClass(Number(event.target.value))}><option value="">Select class</option>{allClasses.map(item => <option key={item.id} value={item.id}>Grade {item.grade}{item.section} · {item.subject}</option>)}</select></label><label className="form-label">Student<select value={selectedStudent ?? ""} onChange={event => setSelectedStudent(Number(event.target.value))}><option value="">Select student</option>{students.slice(0, 100).map(item => <option key={item.id} value={item.id}>{item.name} · {item.class_name}</option>)}</select></label><button className="primary-button full" disabled={!selectedClass || !selectedStudent || placeStudent.isPending} onClick={() => placeStudent.mutate()}>Place student</button></Card></div></>;
  return <><div className="page-heading"><div><span className="eyebrow">School database map</span><h1>Grades 1–12</h1><p>Each grade has its own physical academic database and independently managed sections.</p></div><Badge tone="teal">13 databases active</Badge></div><div className="school-metrics"><Card><Database /><div><strong>12</strong><span>Grade databases</span></div></Card><Card><Building2 /><div><strong>{allClasses.length}</strong><span>Active sections</span></div></Card><Card><Users /><div><strong>{students.length}</strong><span>Students placed</span></div></Card><Card><BookOpenCheck /><div><strong>{teachers.length}</strong><span>Teaching staff</span></div></Card></div><Card className="create-class-card"><div className="card-heading"><div><span className="eyebrow">Section setup</span><h2>Create a class section</h2></div><Plus /></div><form className="create-class-form" onSubmit={event => { event.preventDefault(); createClass.mutate(); }}><label className="form-label">Grade<select value={newClass.grade} onChange={event => { const grade = Number(event.target.value); setNewClass(current => ({ ...current, grade, name: `Grade ${grade}${current.section}` })); }}>{Array.from({ length: 12 }, (_, index) => index + 1).map(grade => <option key={grade} value={grade}>Grade {grade}</option>)}</select></label><label className="form-label">Section<input required maxLength={20} value={newClass.section} onChange={event => { const section = event.target.value.toUpperCase(); setNewClass(current => ({ ...current, section, name: `Grade ${current.grade}${section}` })); }} /></label><label className="form-label">Class name<input required value={newClass.name} onChange={event => setNewClass(current => ({ ...current, name: event.target.value }))} /></label><label className="form-label">Subject<input required value={newClass.subject} onChange={event => setNewClass(current => ({ ...current, subject: event.target.value }))} /></label><button className="primary-button" disabled={createClass.isPending}>{createClass.isPending ? "Creating…" : "Create section"}</button></form>{createClass.error && <ErrorNotice message={(createClass.error as Error).message} />}</Card><div className="grade-grid">{grades.data?.map(item => <Card key={item.grade} className={`grade-card ${item.classes.length ? "grade-active" : ""}`}><div><span>Grade</span><strong>{String(item.grade).padStart(2, "0")}</strong></div>{item.classes.length ? <div className="grade-classes">{item.classes.map(cls => <span key={cls.id}>{cls.section} · {cls.subject}<b>{cls.student_count} students</b></span>)}</div> : <p>Database ready when first section is created</p>}</Card>)}</div></>;
}
